### ISSUE TITLE
Allow optional timeout on Select.ExecuteAsync

### ISSUE THREAD

**Issue by ackginger** [busterwood/BusterWood.Channels#2]
In order to make it simpler to receive on channel with timeout
Currently have to use:

`new Select()`
`                .OnReceive(chan, msg => response = msg.Message as BookingResponse)`
`                .OnReceive(BusterWood.Channels.Timeout.After(timeout ??System.Threading.Timeout.InfiniteTimeSpan), _ => { })`
`                .ExecuteAsync();`

**Comment by busterwood** [comment]
Fixed in version 1.2.0
